apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: flux
spec:
  interval: 1m
  url: oci://ghcr.io/stefanprodan/manifests/podinfo
  ref:
    tag: latest