apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: flux
  prune: true
  sourceRef:
    kind: OCIRepository
    name: podinfo
  path: ./